AllCops:
  Excludes:
    - bin/**
    - config/**
    - db/schema.rb

Documentation:
  Exclude:
    - db/**
    - spec/**

DotPosition:
  Enabled: false

FileName:
  Exclude:
    - db/**

FinalNewline:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Exclude:
    - db/**

IfUnlessModifier:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Exclude:
    - db/**

StringLiterals:
  Enabled: false

WordArray:
  Enabled: false

Encoding:
  Enabled: false
