AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  RunRailsCops: true

AbcSize:
  Max: 40

ClassLength:
  Max: 200

CyclomaticComplexity:
  Max: 10

MethodLength:
  Max: 35
